version: "3"
services:
  keydb:
    image: eqalpha/keydb:alpine
    container_name: nooim-keydb
    command: keydb-server --maxclients 100000 --server-threads 2 --protected-mode no
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
